const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('reactor', {
	openScriptsFolder: () => ipcRenderer.invoke('open-scripts-folder'),
	openScriptFile: (filePath) => ipcRenderer.invoke('open-script-file', filePath),
	readScriptContent: (filePath) => ipcRenderer.invoke('read-script-content', filePath),
	saveScriptContent: (filePath, content) => ipcRenderer.invoke('save-script-content', filePath, content),
	resolveEventLogPath: (filePath) => ipcRenderer.invoke('resolve-event-log-path', filePath),
	runScriptNow: (filePath) => ipcRenderer.invoke('run-script-now', filePath),
	createScriptFile: (templateKey, scriptName) => ipcRenderer.invoke('create-script-file', templateKey, scriptName),
	deleteScriptFile: (filePath) => ipcRenderer.invoke('delete-script-file', filePath),
	renameScriptFile: (filePath, nextName) => ipcRenderer.invoke('rename-script-file', filePath, nextName),
	confirmDeleteScript: (scriptName) => ipcRenderer.invoke('confirm-delete-script', scriptName),
	toggleScriptDirective: (filePath, directive) => ipcRenderer.invoke('toggle-script-directive', filePath, directive),
	getScriptsInfo: () => ipcRenderer.invoke('get-scripts-info'),
	getUiSettings: () => ipcRenderer.invoke('get-ui-settings'),
	pickDefaultProgram: () => ipcRenderer.invoke('pick-default-program'),
	openEventLog: (filePath) => ipcRenderer.invoke('open-event-log', filePath),
	clearEventLog: (filePath) => ipcRenderer.invoke('clear-event-log', filePath),
	getHttpServerConfig: () => ipcRenderer.invoke('get-http-server-config'),
	setHttpServerPort: (port) => ipcRenderer.invoke('set-http-server-port', port),
	getHttpServerLogs: (limit) => ipcRenderer.invoke('get-http-server-logs', limit),
	openServerStatus: () => ipcRenderer.invoke('open-server-status'),
	getReactorName: () => ipcRenderer.invoke('get-reactor-name'),
	setReactorName: (name) => ipcRenderer.invoke('set-reactor-name', name),
	getWorkflow: () => ipcRenderer.invoke('get-workflow'),
	saveWorkflow: (workflow) => ipcRenderer.invoke('save-workflow', workflow),
	getExchangeConfig: () => ipcRenderer.invoke('get-exchange-config'),
	setExchangeConfig: (mode, host, port, tls, token) => ipcRenderer.invoke('set-exchange-config', { mode, host, port, tls, token }),
	getExchangeToken: () => ipcRenderer.invoke('get-exchange-token'),
	generateExchangeToken: () => ipcRenderer.invoke('generate-exchange-token'),
	getTlsConfig: () => ipcRenderer.invoke('get-tls-config'),
	generateTlsCert: () => ipcRenderer.invoke('generate-tls-cert'),
	deleteTlsCert: () => ipcRenderer.invoke('delete-tls-cert'),
	exportBackup: () => ipcRenderer.invoke('export-backup'),
	importBackup: () => ipcRenderer.invoke('import-backup'),
});
