declare module 'core' {
	/** Custom HTTP headers map used in Node calls. */
	export type HeadersMap = Record<string, string>;

	/**
	 * Additional options for Node.sendMessage(...).
	 */
	export interface NodeSendMessageOptions {
		/** Custom HTTP headers sent to the target node. */
		headers?: HeadersMap;
	}

	/**
	 * Options for Node.stream(...).
	 */
	export interface NodeStreamOptions {
		/** Chunk size in bytes (best effort). */
		chunkSize?: number;
		/** Stream content type (for example application/octet-stream). */
		contentType?: string;
		/** Optional metadata attached to the stream. */
		metadata?: Record<string, unknown>;
		/** Expected total number of bytes, when known. */
		totalBytes?: number;
		/** Custom HTTP headers for direct stream delivery. */
		headers?: HeadersMap;
		/** Forced stream ID (otherwise generated by the runtime). */
		streamId?: string;
	}

	export type NodeStreamSource =
		| ReadableStream<Uint8Array>
		| AsyncIterable<Uint8Array | Buffer | string | ArrayBuffer>
		| Iterable<Uint8Array | Buffer | string | ArrayBuffer>
		| Uint8Array
		| Buffer
		| string
		| ArrayBuffer;

	export interface NodeStreamResponse {
		/** Original target passed to the call. */
		target: string;
		/** Transport used: direct (HTTP) or exchange (WS). */
		via: 'direct' | 'exchange';
		/** Unique stream identifier. */
		streamId: string;
		/** Number of chunks sent. */
		chunks: number;
		/** Total bytes sent. */
		totalBytes: number;
		/** Sender-side SHA-256 payload digest. */
		digestSha256: string;
	}

	export interface NodeSendMessageResponse {
		/** Original target passed to the call. */
		target: string;
		/** HTTP endpoint used when available. */
		endpoint?: string;
		/** HTTP status when direct transport is used. */
		status?: number;
		/** Response headers when available. */
		headers?: HeadersMap;
		/** Response body when available. */
		body?: string;
		/** Transport used when known. */
		via?: 'direct' | 'exchange';
		/** True when the message has been queued. */
		queued?: boolean;
		/** Short reason in queue/fallback scenarios. */
		reason?: string;
	}

	export interface NodeExchangeSendMessageResponse {
		target: string;
		via: 'exchange';
		queued: true;
	}

	export interface NodeExchangeApi {
		/**
		 * Sends a message forcing Exchange transport.
		 *
		 * @param target Supported formats:
		 * - node_name
		 * - node_name/script_uuid
		 * - host_or_ip:port
		 * - host_or_ip:port/script_uuid
		 */
		sendMessage: (
			target: string,
			content: string | Uint8Array | Buffer | Record<string, unknown>,
		) => Promise<NodeExchangeSendMessageResponse>;

		/**
		 * Sends a stream forcing Exchange transport.
		 *
		 * @param target Supported formats:
		 * - node_name
		 * - node_name/script_uuid
		 * - host_or_ip:port
		 * - host_or_ip:port/script_uuid
		 */
		stream: (
			target: string,
			source: NodeStreamSource,
			options?: Omit<NodeStreamOptions, 'headers'>,
		) => Promise<NodeStreamResponse>;
	}

	export interface NodeApi {
		/**
		 * Sends a message to a Reactor node.
		 *
		 * @param target Supported formats:
		 * - node_name
		 * - node_name/script_uuid
		 * - host_or_ip
		 * - host_or_ip:port
		 * - host_or_ip/script_uuid
		 * - host_or_ip:port/script_uuid
		 *
		 * If /script_uuid is provided, the message is routed only to that target project.
		 */
		sendMessage: (
			target: string,
			content: string | Uint8Array | Buffer | Record<string, unknown>,
			options?: NodeSendMessageOptions,
		) => Promise<NodeSendMessageResponse>;

		/**
		 * Sends a binary/text stream to a Reactor node.
		 *
		 * @param target Supported formats:
		 * - node_name
		 * - node_name/script_uuid
		 * - host_or_ip
		 * - host_or_ip:port
		 * - host_or_ip/script_uuid
		 * - host_or_ip:port/script_uuid
		 */
		stream: (
			target: string,
			source: NodeStreamSource,
			options?: NodeStreamOptions,
		) => Promise<NodeStreamResponse>;

		/**
		 * Returns the explicit Exchange API (always sends through Exchange).
		 */
		exchange: () => NodeExchangeApi;
	}

	export type LogLevel = 'E' | 'W' | 'I' | 'D';
	/** Writes to activity.log of the current runtime. */
	export function log(message: string, type?: LogLevel): Promise<void> | void;
	/** Node API globally available in Reactor scripts. */
	export const Node: NodeApi;
}

declare const Node: import('core').NodeApi;
declare function log(message: string, type?: import('core').LogLevel): Promise<void> | void;
